### ISSUE TITLE
StreetVoiceLoader not working

### ISSUE THREAD

**Issue by seth-js** [TheLastZombie/userscripts#20]
The StreetVoiceLoader userscript isn't working properly.

The download button is added to the .list-item-buttons element without issues. However, it leads to URLs like: `https://streetvoice.com/collage7275/songs/622036/undefined`.

![undefined](https://user-images.githubusercontent.com/83692925/175462559-0bef95d0-d930-41b5-81ae-797312ff66f4.png)

`https://streetvoice.com/api/v3/songs/622036/file/` leads to this JSON file:
![message](https://user-images.githubusercontent.com/83692925/175461802-03b3e1d3-628c-4a2c-a53e-dd9740d3c71a.png)

I tested this on both ViolentMonkey (Firefox) and TamperMonkey (Chrome).

**Comment by seth-js** [comment]
Just tried making an account, then reloading, but the response is still the same. They've most likely blocked this method of getting the MP3.

**Comment by TheLastZombie** [comment]
Yeah, it seems like they went from plain MP3 files to HLS streams. I'm currently working on an update, but the script needs a major rewrite in order to download the new files properly.

**Comment by seth-js** [comment]
No problem. I'll just use youtube-dl in the meantime. Hopefully you'll be able to get this sorted out soon.

**Comment by TheLastZombie** [comment]
Should've been fixed with 2.0.0.

**Comment by seth-js** [comment]
Thanks. It's working with Chrome now.

Firefox is still not working for some reason. I'm getting back `urls[i] is undefined` in the console. The response text is returning `{"error":{"message":"CSRF Failed: Referer checking failed - no Referer.","code":"0","detail":{}}}`

**Comment by TheLastZombie** [comment]
Interesting, I just tried it again in a new Firefox profile with only Violentmonkey and the script installed, and it works fine for me. Maybe there's another extension or userscript interfering with StreetVoiceLoader.

I created a version of the script with some logging, which will hopefully help me pin down the issue. Could you try it and share the `log` value?

![image](https://user-images.githubusercontent.com/8181990/175767925-a86fcbb1-df99-471b-87e8-759a1514b379.png)

[Here's the script.](https://gist.github.com/TheLastZombie/ec3be69a8584483592022d4ef0fe4d70/raw/cab34ff9cdf535535fff1b056bbf7de0a4b4e959/StreetVoiceLoader.user.js) Make sure to disable the release/"normal" version while the debug build is enabled.

**Comment by seth-js** [comment]
The log value is `[SVL] IDs: 622036\n[SVL] URL: https://streetvoice.com/api/v5/song/622036/hls/file/\n[SVL] Retrieving TS URLs for track 1...`, then the same `TypeError: urls[i] is undefined` error stops the script. I've disabled every other extension, and ViolentMonkey says the only matched script is the StreetVoice one.

**Comment by seth-js** [comment]
I made a new profile, installed ViolentMonkey, and installed your script. Everything works. This means that it's most likely one of my Firefox settings breaking the script, although I am not sure which one.

**Comment by TheLastZombie** [comment]
Seems like there's something fishy going on in the request to https://streetvoice.com/api/v5/song/622036/hls/file/ ﻿– the script can't retrieve the M3U8 URL for the track. Does it fail at the same step when trying to download an album too, or does it already fail at the https://streetvoice.com/api/v5/album/ID/songs/?limit=100 request there?

The request doesn't need referrers, cookies or anything like that, but I can't really think of any non-privacy-related preferences that may cause this to happen either. Do you remember tinkering with `about:config` at some point?

Which Firefox version and OS are you using? Also, could you try running the following snippet in the browser console on any StreetVoice page and share the result?

```JS
fetch("https://streetvoice.com/api/v5/song/622036/hls/file/", {
  method: "POST"
})
  .then(response => response.text())
  .then(data => console.log(data))
  .catch(error => console.error(error));
```

Finally, could you try sending a `POST` request to the URL from another tool to see if it goes through? For example:

```Shell
iwr -Method POST -Uri https://streetvoice.com/api/v5/song/622036/hls/file/ # on Windows, using PowerShell
curl -X POST https://streetvoice.com/api/v5/song/622036/hls/file/          # on Linux, using Bash
```

**Comment by seth-js** [comment]
Here's the log value for an album:
`[SVL] URL: https://streetvoice.com/api/v5/album/7016/songs/?limit=100\n[SVL] IDs: 96528,96511,96512,21248,27390,44453\n[SVL] URL: https://streetvoice.com/api/v5/song/96528/hls/file/\n[SVL] URL: https://streetvoice.com/api/v5/song/96511/hls/file/\n[SVL] URL: https://streetvoice.com/api/v5/song/96512/hls/file/\n[SVL] URL: https://streetvoice.com/api/v5/song/21248/hls/file/\n[SVL] URL: https://streetvoice.com/api/v5/song/27390/hls/file/\n[SVL] URL: https://streetvoice.com/api/v5/song/44453/hls/file/\n[SVL] Retrieving TS URLs for track 1...`, then it crashes again.

I have changed values of `about:config` before. Although, I can't remember which ones.

I'm running Firefox 101.0.1 (64-bit) on Windows 10.

I ran the snippet you posted, and this is the error I got:
![error](https://user-images.githubusercontent.com/83692925/175826092-93cbdeda-944f-4d62-a217-0ddd1f38f157.png)

I ran `iwr -Method POST -Uri https://streetvoice.com/api/v5/song/622036/hls/file/`, and in the `Content` field I can see this:
`{"file":"https://akhls.streetvoice.com/music/co/ll/collage7275/Nf7zffpYqdLoiuDWgwx3o3.mp3.128khls.mp3.m3u8"}`

I hate to bother you like this. I'm sure your script works. It's just that there's something weird I must have done to this Firefox profile.

**Comment by TheLastZombie** [comment]
No worries, I'm probably just as interested in fixing this as you are :-)

Long shot, but are you logged in to StreetVoice? And when you tried it in a new Firefox profile, you weren't? I don't actually have an account, so I can only confirm that it works without one.

**Comment by seth-js** [comment]
You solved it. I signed out, and now the script works. Having an account logged in messes up the script somehow. Everything's working as expected now. Thanks for working hard to solve this issue.
